# Generated by Django 3.0.5 on 2020-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URLID', models.CharField(max_length=1000)),
                ('ShortURL', models.CharField(max_length=1000)),
            ],
        ),
    ]
